languague: groovy
before_install:
  - gem install asciidoctor
  - gem install asciidoctor-diagram
  - gem install prawn --version 1.3.0
  - gem install --pre asciidoctor-pdf
  - gem install rouge
  - sudo apt-get update -qq
  - sudo apt-get install -y graphviz
script: "./gradlew publishGhPages"
cache:
  directories:
  - $HOME/.gradle
env:
  global:
    secure: Bp3vNi1MYNSSti7RaF/Ag7uCJsJN5FqOFlgW79vZIIbPyK5i8GDvTCcLI5rtLZOL2taJeg6h4mxpywZVjHxqQTcZNO4swmBpaucglQkd4Dw2wfijODU7GAttkf8vCNHDJfs3EoPLVZ+HnyqKjXr7RYfHBoSzsXpTx1BNETaefRLM/Pti50JbbXJnJlCZH0Tiaj5Glxwp4utZ4S4nETXeeE4K73lNa33Lv8krB8g4VnaAMeRosu4+cu7zHb/xG0uIsAwGPGdZZkaalu+2E2dHrZGjTJtqUZp8PGXH1v85N97HqVCUMVAaqRllgrM/6SHThgSYUKzc3mjdlwnoPpUwS5RWyakOFadGQyAh5owEh9c4aXlL+Nd5YFoX5STaHdmlBjEzViVGZX3lEaXVF0FNwLKooOq5z/xiC+Rv02iNbT+kOC4wXqVr2DJyCKV49T41LVZDW6TqOuAERyPxUWlPpTCpv746n8D4Pjh6nRDR8Zn2qSup+qoZY2hEc7AIGsQUwfgZlnXkb+idW/fYtqL0AhyTWxrZOpwIPGO0zUYJwzQ2lLGY42A0udpyRazCppNcx9N/S3zIiRvykjZMvJGPxXHKSerfxMqE5M/Z8E/yLnxdFCZO5A92BuFiSw7lBB2qByY+qWPVXbvs2PTRyi+YxxZApcP/M9apaEyn4GZmE+E=
